# Generated by Django 3.1.8 on 2021-05-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0002_custom_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancefeature',
            name='config_type',
            field=models.CharField(default='cli', max_length=20),
        ),
    ]
