# Generated by Django 3.1.8 on 2021-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_golden_config', '0003_auto_20210503_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcompliance',
            name='compliance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
