# Generated by Django 3.1.8 on 2021-05-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_initial_part_4'),
        ('nautobot_golden_config', '0004_auto_20210503_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configcompliance',
            old_name='name',
            new_name='feature',
        ),
        migrations.AlterUniqueTogether(
            name='configcompliance',
            unique_together={('device', 'feature')},
        ),
    ]
